name: CI

on:
  push:
    branches:
      - "**"
  release:
    types:
      - created

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build
      - name: Publish to VS Marketplace
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: npx vsce publish --web
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
